spring.application.name=kosten

spring.datasource.url=jdbc:postgresql://localhost:5432/kosten
spring.datasource.username=kosten
spring.datasource.password=kosten
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
